language: java

before_install:
- sudo apt-get -qq update
# ant-optional is needed for ant junit
- sudo apt-get install ant-optional

script:
  - ant test -lib ./lib/junit-4.12.jar ./lib/hamcrest-core-1.3.jar

branches:
  only:
  - master
