language: java

before_install:
-  sudo apt-get -qq update
 # ant-optional is needed for ant junit
 - sudo apt-get install ant-optional
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
  - ant -verbose test -lib ./lib/junit-4.12.jar ./lib/hamcrest-core-1.3.jar

branches:
  only:
  - master
